config/routes.rb
Rails.application.routes.draw do
  get 'grayscales/index'
  root to: 'grayscales#index'
  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message 
  include ActiveModel::Model
  attr_accessor :name, :email, :phone, :body
  validates :name, :email, :phone, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/grayscales_controller.rb
class GrayscalesController < ApplicationController
  layout "grayscale"
    def index
      @message = Message.new
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end
  def create
    @message = Message.new message_params

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to root_path, notice: "Message received, thanks!"
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :phone, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/grayscales/_about.html.erb
<div id= "about" class="row featurette mystory center center">
        <div class="col-md-1"></div>
        <div class="col-md-6">
          <h2 class="featurette-heading"> My Story <span class="text-muted text-lowercase" style='font-size: 24px;'>Dedicated to finding your perfect home</span></h2>
          <p class="lead" style='font-size: 18px;'>Purchasing a home is an immensely important life event for everyone. Finding the perfect living space, neighborhood, and amenities can be overwhelming at times. Working with a realtor who takes the time to truly understand what you are looking for is critical to finding your perfect fit. I take pride in matching my clients with their ideal homes in Metro Detroit. If you are looking for a realtor who will tirelessly work to find your match, look no further.   </p>
          <br>
          <br>
          <a href="#market" class="btn page-scroll aboutbtn">
            <i class="fa fa-angle-double-down animated"></i>
          </a>
        </div>

        <div class=" col-md-5 portrait">
          <img class="img-rounded img-fluid center-block" src="http://www.redata.com/100042/reo/agents/474769ax.jpg">
        </div>
</div>

app/views/grayscales/_contact.html.erb
<hr class="featurette-divider">
<div id="contact" class="contactfeat"></div>
<%= form_for @message, url: create_message_url do |f| %>
<%= notice %>
<%= @message.errors.full_messages.join(', ') %>
      <div class="container ">
          <div class="row">
              <div class="col-md-8 col-md-offset-2 m-auto">
                  <div class="jumbotron thirdjumbo">
                      <div class="container display-3 text-center contactjumbo">
                          <h1>Contact</h1>
                      </div>
                  </div> 
                  <div class="contact-form text-center">
                      <p class="hint-text">Let's find your next home! Please fill out the information below and I will contact you for a free consultation. </p>
                      <form action="/examples/actions/confirmation.php" method="post">           
                          <div class="form-group">
                              <label for="inputFirstName">Name</label>
                              <%= f.text_field :name, class: "form-control", id:"inputName" %>
                          </div>                                  
                          <div class="form-group">
                              <label for="inputEmail">Email Address</label>
                              <%= f.email_field :email, class: "form-control", id:"inputEmail"  %>
                          </div>
                          <div class="form-group">
                              <label for="inputPhone">Phone Number</label>
                              <%= f.telephone_field :phone, class: "form-control" %>
                          </div>
                          <div class="form-group">
                              <label for="inputMessage">Message</label>
                              <%= f.text_area :body, class: "form-control", id:"inputMessage", rows: "5" %>
                          </div>
                          <%= f.submit type="submit", class: "btn btn-primary", value: "Submit"%>
                      </form>
                  </div>
              </div>
          </div>
      </div>
<% end %>
      

app/views/grayscales/_footer.html.erb
<footer>
    <div class="container text-center">
        <p style="font-size: 10px"> Website Created by John Ristau <%= Time.now.year %></p>
    </div>
</footer>

app/views/grayscales/_header.html.erb
<header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h1 class="brand-heading">John Lee Realty</h1>
                    <p class="intro-text">Let's Find You a Home<br></p>
                    <a href="#about" class="btn btn-circle page-scroll">
                        <i class="fa fa-angle-double-down animated"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/grayscales/_map.html.erb
<div id="map">
	    <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/d/embed?mid=16B2SsdjYifwJLTgii9-aljmb7CU&hl=en" width="640" height="480"></iframe>
    <br />
    <small>
        <a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A"></a>
    </small>
    </iframe>
</div>

app/views/grayscales/_market.html.erb
<hr class="featurette-divider">

  <div id="market" class="row featurette market">
    <div class="col-md-5">
          <span class="glyphicon glyphicon-stats"></span>
    </div>
    <div class="col-md-6">
      <h2 class="featurette-heading">Market Trends<span class="text-muted text-lowercase" style='font-size: 24px;'> Expertise on the housing market in Metro Detroit</span></h2>
      <p class="lead">The housing market is constantly evolving, and Metro Detroit has seen some major changes in recent years. Keeping up to date on trends in the market is critical to finding a home that makes sense for the present and future. If you are interested in researching current trends in the market, click here to view my personal blog on the housing market in Metro Detroit.  </p>
      <br>
      <br>
      <a href="#review" class="btn page-scroll marketbtn">
        <i class="fa fa-angle-double-down animated"></i>
      </a>
    </div>
    <div class="col-md-1"></div>
  </div>

app/views/grayscales/_navigation.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">
                <i class="fa fa-home"></i>  <span class="light">John Lee</span> Realty
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a class="page-scroll" href="#about">About Me</a>
                </li>
                <li>
                    <a class="page-scroll" href="#market">Market Tips</a>
                </li>
                <li>
                    <a class="page-scroll" href="#review"> Testimonials</a>
                </li>
                <li> 
                    <a class="page-scroll" href="#contact">Contact Me</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/grayscales/_review.html.erb
<hr class="featurette-divider">

  <div id= "review" class="row featurette customer">
    <div class="col-md-1"></div>
    <div class="col-md-6">
      <h2 class="featurette-heading">Dedicated to Customer Satisfaction<span class="text-muted text-lowercase" style='font-size: 24px;'> See what former clients have to say</span></h2>
      <p class="lead"> My main concern is always the satisfaction of my clients. Going above and beyond what is expected from a realtor is what I strive for. Whether you need help buying or selling a home, I will be there with you every step of the way. Please visit any of the pages below to see what former clients have to say about working with me.</p>

      <ul class="list-inline list-social-icons">
        <li class="list-inline-item">
          <a href="#">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
            </span>
          </a>
        </li>
        <li class="list-inline-item">
          <a href="#">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
            </span>
          </a>
        </li>
        <li class="list-inline-item">
          <a href="#">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
            </span>
          </a>
        </li>
        <li class="list-inline-item">
          <a href="#">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
            </span>
          </a>
        </li>
      </ul>
    </div>
    

    <div class="col-md-5">
      <span class="glyphicon glyphicon-thumbs-up"></span>
    </div>
    <a href="#contact" class="btn page-scroll reviewbtn">
      <i class="fa fa-angle-double-down animated"></i>
    </a>
  </div>

app/views/grayscales/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/grayscales/index.html.erb
	<%= render 'shim' %>
	<%= render 'navigation' %>
	<%= render 'header' %>
	<%= render 'about' %>
  <%= render 'market' %>
  <%= render 'review' %>
	<%= render 'contact' %>
	<%= render 'map' %>
	<%= render 'footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jlrealty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/grayscale.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> John Lee Realty</title>
  <%= stylesheet_link_tag 'grayscale/manifest.css', media: 'all' %>
  <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet" rel="stylesheet" type="text/css">
  <%= javascript_include_tag 'grayscale/manifest.js' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<%= yield %>

</body>
</html>

app/views/messages/new.html.erb
<%= form_for @message, url: create_message_url do |f| %>
  <%= notice %>
  <%= @message.errors.full_messages.join(', ') %>
        <div class="container ">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 m-auto">
                    <div class="jumbotron thirdjumbo">
                        <div class="container display-3 text-center contactjumbo">
                            <h1>Contact</h1>
                        </div>
                    </div> 
                    <div class="contact-form text-center">
                        <p class="hint-text">Let's find your next home! Please fill out the information below and I will contact you for a free consultation. </p>
                        <form action="/examples/actions/confirmation.php" method="post">           
                            <div class="form-group">
                                <label for="inputFirstName">Name</label>
                                <%= f.text_field :name, class: "form-control", id:"inputName" %>
                            </div>                                  
                            <div class="form-group">
                                <label for="inputEmail">Email Address</label>
                                <%= f.email_field :email, class: "form-control", id:"inputEmail"  %>
                            </div>
                            <div class="form-group">
                                <label for="inputPhone">Phone Number</label>
                                <%= f.telephone_field :phone, class: "form-control" %>
                            </div>
                            <div class="form-group">
                                <label for="inputMessage">Message</label>
                                <%= f.text_area :body, class: "form-control", id:"inputMessage", rows: "5" %>
                            </div>
                            <%= f.submit type="submit", class: "btn btn-primary", value: "Submit"%>
                        </form>
                    </div>
                </div>
            </div>
        </div>
<% end %>